#!/bin/bash
#
# apache paigaldus
#
#
# apache2 teenus olemasolu kontroll
APACHE2=$(dpkg-query -W -f='${Status}' apache2 2>/dev/null | grep -c "installed")
# tulemus on kas 0 või 1 kui ridade arv on 0 - pole paigaldatud
# apache2 paigaldus
if [ $APACHE2 -eq 0 ]; then
 	echo "Paigaldame apache2"
 	apt-get install -y apache2;
# kui ridade arv on 1, siis teenus on paigaldatud
elif [ $APACHE2 -eq 1 ]; then
 	echo "Apache2 on paigaldatud"
# staatuse näitamine
	service apache2 status
fi 
