#!/bin/bash
#
#Wordpress install
#
#
#
echo "Kas Apache on installitud? (y/n)"
read -e apache
if [ "$apache" == "n" ]; then
echo "Paigaldame apache2"
	sudo apt-get install apache2;
clear
echo "Taaskaivita script palun"
elif [ "$apache" == "y" ]; then
echo "Kas PHP moodulid on installitud? (y/n)"
read -e php
if [ "$php" == "n" ]; then
echo "Paigaldame PHP moodulid"
sudo apt-get install php7.0 php7.0-mysql libapache2-mod-php7.0 php7.0-cli php7.0-cgi php7.0-gd;
clear
echo "Taaskaivita script palun"
elif [ "$php" == "y" ]; then
echo "Kas phpMyadmin on installitud? (y/n)"
read -e phpmy
if [ "$phpmy" == "n" ]; then
echo "Paigaldame phpMyadmini"
sudo apt-get install phpmyadmin php-mbstring php-gettext;
clear
else
echo "Wordpressi installimine"
fi
echo "============================================"
echo "WordPress Installimise Script"
echo "============================================"
echo "Andmebaasi Nimi: "
read -e dbname
echo "Andmebaasi Kasutaja: "
read -e dbuser
echo "Andmebaasi Parool: "
read -s dbpass
echo "Andmebaasi IP: "
read -e dbip
echo "run install? (y/n)"
read -e run
if [ "$run" == n ] ; then
exit
else
echo "============================================"
echo "Alustame installiga."
echo "============================================"
#download wordpress
curl -O https://wordpress.org/latest.tar.gz
#unzip wordpress
tar -zxvf latest.tar.gz
#change dir to wordpress
cd wordpress
#copy file to parent dir
mkdir /var/www/html/wordpress
cp -rf . /var/www/html/wordpress
#move back to parent dir
cd ..
#remove files from wordpress folder
rm -R wordpress
cd /var/www/html/wordpress
#create wp config
cp wp-config-sample.php wp-config.php
#set database details with perl find and replace
perl -pi -e "s/database_name_here/$dbname/g" wp-config.php
perl -pi -e "s/username_here/$dbuser/g" wp-config.php
perl -pi -e "s/password_here/$dbpass/g" wp-config.php
perl -pi -e "s/localhost/$dbip/g" wp-config.php

#set WP salts
perl -i -pe'
  BEGIN {
    @chars = ("a" .. "z", "A" .. "Z", 0 .. 9);
    push @chars, split //, "!@#$%^&*()-_ []{}<>~\`+=,.;:/?|";
    sub salt { join "", map $chars[ rand @chars ], 1 .. 64 }
  }
  s/put your unique phrase here/salt()/ge
' wp-config.php

#create uploads folder and set permissions
mkdir wp-content/uploads
chmod 775 wp-content/uploads
echo "Korrastame"
#remove zip file
cd ~/ rm latest.tar.gz
sudo apt install mysql-client
echo "========================="
echo "Installimine lopetatud."
echo "========================="
fi
fi
fi
